make sure out directory is available

diff --git a/.github/workflows/deploy-docs.yml b/.github/workflows/deploy-docs.yml
--- a/.github/workflows/deploy-docs.yml
+++ b/.github/workflows/deploy-docs.yml
@@ -41,7 +41,7 @@ jobs:
       - name: Debug output directory
         run: |
           echo "Checking output directory..."
-          ls -la docs/out || echo "Output directory not found!"
+          ls -la docs/.next/standalone || echo "Output directory not found!"
           
       - name: Setup Pages
         uses: actions/configure-pages@v3
@@ -49,7 +49,7 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: docs/out
+          path: docs/.next/standalone
 
   deploy:
     environment:
